[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"
optimizer = true
optimizer-runs = 10_000_000

# solc = "0.8.20"


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
sepolia_base = "${SEPOLIA_BASE_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
sepolia_base = { key = "${ETHERSCAN_API_KEY}" }
