[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"
optimizer = true
optimizer-runs = 10_000_000

# solc = "0.8.20"


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
taiko = "${TAIKO_RPC_URL}"



